#ifndef WINDOW_TEST_RESOURCE_H
#define WINDOW_TEST_RESOURCE_H

#define IDC_STATIC -1

#define IDI_MYEXEICON 201
#define IDI_MYICON 202

#define IDR_MYMENU 101
#define ID_FILE_OPEN 9001
#define ID_FILE_SAVE 9002
#define ID_FILE_ABOUT 9003
#define ID_FILE_EXIT 9004

#define IDD_ABOUT 301

#endif