#ifndef PICTURE_PREPROCESSOR_RESOURCE_H
#define PICTURE_PREPROCESSOR_RESOURCE_H

#define IDC_STATIC -1

#define IDI_MYEXEICON 201
#define IDI_MYICON 202

#define IDD_SELECTDIRECTORY 301

#define IDC_SELECTINPUTDIRECTORY 401
#define IDC_INPUTDIRECTORY 402
#define IDC_SELECTOUTPUTDIRECTORY 403
#define IDC_OUTPUTDIRECTORY 404
#define IDC_STARTBUTTON 405

#endif